### ISSUE TITLE
Do you need taggers everywhere?

### ISSUE THREAD

**Issue by league** [emtenet/elm-component-support#1]
Hi, this project is a great idea! I like the way `Update.Action` unifies things.

The one thing that I felt was a little awkward was having to pass around these `(msg1->msg2)` tagging functions everywhere. I wondered, with the existence of:
- `Html.App.map : (a -> msg) -> Html a -> Html msg`
- `Platform.Sub.map : (a -> msg) -> Sub a -> Sub msg`
- `Platform.Cmd.map : (a -> msg) -> Cmd a -> Cmd msg`

do we need tag arguments at all? Rather than call:

``` elm
    childView (tag << Thing) model.child
```

Can we instead rely on:

``` elm
    Html.App.map Thing <| childView model.child
```

I took a crack at that, got all 5 example programs to work, and in my view it seems a little simpler. You can browse what I did on this branch: https://github.com/league/elm-component-support/commits/remove-taggers

I didn't try to remove the `tag` argument throughout the `Update` module — really it's only the `view` and `subscription` functions in the `App` module. The other place that I left a `tag` argument alone was in example 4, `Counter.viewWithButtons`. What you're doing there is embedding a 'parent' HTML within the child's HTML, so the `tag` was harder to remove. And I think using a tag only in situations like this instead of everywhere would be better.

Let me know what you think! Thanks.

**Comment by emtenet** [comment]
Thanks for the interest in this project.

You are right that views can be composed in two ways, passing taggers around as I have used so far or the `Http.App.map` function. And I agree that passing taggers around may well be the more awkward of the two options.

At the moment users of this package can use either view composition pattern they wish (except at the `Component.App.program` boundary). And so the documentation should outline the two patterns and let uses choose as best suits.

Lets call the two patterns of view composition, the tagger pattern, and the map pattern.

Whilst this project is still being explored I am tempted to leave the examples using the tagger pattern for the following reasons:
1. The tagger pattern can do special cases such as `Counter.viewWithButtons` that the map pattern cannot.
2. The tagger pattern is not as obvious as the map pattern and so using it in examples raises awareness of the pattern.
3. `update` functions can also be composed by passing taggers or mapping the return values. The `Update.Action` functions I am working on greatly benefit from the tagger pattern and so using the same pattern for the `view` functions lends a bit of symmetry. It will be interesting to see which patterns are the most appropriate for `init` and `subscription` function composition.
4. My personal favourite at the moment is the tagger pattern as it passes the tagging responsibility to the child component making the parent component cleaner.

**Comment by emtenet** [comment]
As an aside, if I was to use the `Http.App.map` function I would be tempted to rearrange:

```
Html.App.map Password <| TextBox.view model.password
```

as

```
TextBox.view model.password |> Html.App.map Password
```

I want to be focusing on the `.password` and `Password` parts which neither does well but at least `TextBox.view` at the start is more informative than the generic `Http.App.map`. My second version of `Update.Action` is aiming to have `TextBox.update` at the front also instead of `Update.component`.

**Comment by league** [comment]
Interesting ideas, thanks. I'm not using this library currently, but it has helped me think about how to structure messaging between components. I'm not convinced the "Elm Architecture Tutorial" is the last word on it.

No need to keep this issue open though.
